# Generated by Django 3.2.12 on 2022-06-06 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20220514_2007'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('Reg_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('P_type', models.TextField()),
                ('P_ratings', models.FloatField()),
                ('P_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('U_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
