# Generated by Django 3.2.12 on 2022-06-04 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('P_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('P_name', models.TextField()),
                ('P_value', models.FloatField()),
                ('P_type', models.TextField()),
                ('P_ratings', models.FloatField()),
                ('P_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.Seller')),
            ],
        ),
    ]
