# Generated by Django 3.2.12 on 2022-06-15 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='P_value',
        ),
    ]
