# Generated by Django 3.2.12 on 2022-06-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_p_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='P_value',
            field=models.DecimalField(decimal_places=2, max_digits=256, null=True),
        ),
    ]
