# Generated by Django 3.2.12 on 2022-04-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
    ]
