# Generated by Django 3.2.12 on 2022-05-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220514_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='latidude',
            field=models.DecimalField(decimal_places=10, max_digits=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=256, null=True),
        ),
    ]
