# Generated by Django 3.2.12 on 2022-06-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220614_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='latidude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
