# Generated by Django 3.2.12 on 2022-06-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220614_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='latidude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
