# Generated by Django 3.2.12 on 2022-06-15 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20220614_1924'),
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='S_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', unique=True),
        ),
    ]
