# Generated by Django 3.2.12 on 2022-06-04 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20220514_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_input', models.TextField()),
                ('text_input', models.TextField()),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
