# Generated by Django 3.2.12 on 2022-06-11 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
        ('chat', '0002_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='U_id_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.Seller'),
        ),
    ]
