# Generated by Django 3.2.12 on 2022-06-11 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220514_2007'),
        ('chat', '0003_alter_chat_u_id_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='U_id_sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='U_id_sender', to='user.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='U_id_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='U_id_receiver', to='user.user'),
        ),
    ]
