# Generated by Django 3.2.12 on 2022-06-15 23:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20220611_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='text2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
